version: '2'
services:
  db:
    image: postgres:9.4.1
    ports:
      - "5432:5432"

  web:
    build: .
    command: bin/rails server --port 3000 --pid tmp/pids/server2.pid --binding 0.0.0.0
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "3001:3000"
    links:
      - db
    volumes:
      - .:/myapp
