default: &default
  adapter: postgresql
  pool: 5
  username: postgres
  host: db

development:
  <<: *default
  database: rails_heroku_mailgun_development

test:
  <<: *default
  database: rails_heroku_mailgun_test

production:
  <<: *default
  password: <%= ENV['DB_PASSWORD'] %>
  database: rails_heroku_mailgun
