default: &default
  adapter: postgresql
  pool: 5
  username:  <%= ENV['DB_USER'] %>
  host:  <%= ENV['DB_HOST'] %>
  port:  <%= ENV['DB_PORT'] %>

development:
  <<: *default
  database: rails_heroku_mailgun_development

test:
  <<: *default
  database: rails_heroku_mailgun_test

production:
  <<: *default
  password: <%= ENV['DB_PASSWORD'] %>
  database: rails_heroku_mailgun
